# Generated by Django 4.0.4 on 2022-05-04 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berries', models.CharField(blank=True, choices=[('Blackberry', 'Ежевика'), ('Raspberry', 'Малина'), ('Blueberry', 'Голубика'), ('Strawberry', 'Клубника')], max_length=20, verbose_name='Ягоды')),
                ('decor', models.CharField(blank=True, choices=[('Pistachios', 'Фисташки'), ('Meringue', 'Безе'), ('Hazelnuts', 'Фундук'), ('Pecan', 'Пекан'), ('Marshmallow', 'Маршмеллоу'), ('Marzipan', 'Марципан')], max_length=20, verbose_name='Декор')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Надпись')),
                ('levels', models.CharField(choices=[(1, '1 уровень'), (2, '2 уровня'), (3, '3 уровня')], max_length=20, verbose_name='Уровни')),
                ('toppings', models.CharField(choices=[('Without', 'Без топпинга'), ('White sauce', 'Белый соус'), ('Caramel', 'Карамельный'), ('Maple', 'Кленовый'), ('Blueberry', 'Черничный'), ('Milk chocolate', 'Молочный шоколад'), ('Strawberry', 'Клубничный')], max_length=20, verbose_name='Топпинг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes_store.cake', verbose_name='Торт')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
    ]
