# Generated by Django 4.0.4 on 2022-05-06 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('username', models.CharField(max_length=150, verbose_name='имя')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berries', models.CharField(blank=True, choices=[('Blackberry', 'Ежевика'), ('Raspberry', 'Малина'), ('Blueberry', 'Голубика'), ('Strawberry', 'Клубника')], max_length=20, verbose_name='Ягоды')),
                ('decor', models.CharField(blank=True, choices=[('Pistachios', 'Фисташки'), ('Meringue', 'Безе'), ('Hazelnuts', 'Фундук'), ('Pecan', 'Пекан'), ('Marshmallow', 'Маршмеллоу'), ('Marzipan', 'Марципан')], max_length=20, verbose_name='Декор')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Надпись')),
                ('levels', models.CharField(choices=[('1', '1 уровень'), ('2', '2 уровня'), ('3', '3 уровня')], max_length=20, verbose_name='Уровни')),
                ('toppings', models.CharField(choices=[('Without', 'Без топпинга'), ('White sauce', 'Белый соус'), ('Caramel', 'Карамельный'), ('Maple', 'Кленовый'), ('Blueberry', 'Черничный'), ('Milk chocolate', 'Молочный шоколад'), ('Strawberry', 'Клубничный')], max_length=20, verbose_name='Топпинг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60, verbose_name='Имя')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона')),
                ('customer_address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes_store.cake', verbose_name='Торт')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordering', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
    ]
