# Generated by Django 4.0.4 on 2022-05-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='levels',
            field=models.CharField(choices=[('1', '1 уровень'), ('2', '2 уровня'), ('3', '3 уровня')], max_length=20, verbose_name='Уровни'),
        ),
    ]
