# Generated by Django 4.0.4 on 2022-05-07 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='cake',
            name='shape',
            field=models.CharField(choices=[('circle', 'Круг'), ('square', 'Квадрат'), ('rectangle', 'Прямоугольник')], default='Circle', max_length=20, verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cake', to='cakes_store.cake', verbose_name='Торт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_customer', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
