# Generated by Django 4.0.4 on 2022-05-09 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0002_alter_order_options_cake_shape_alter_order_cake_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_address',
            new_name='order_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60, verbose_name='Имя')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_customer', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes_store.order', verbose_name='Заказ')),
            ],
        ),
    ]
