# Generated by Django 4.0.4 on 2022-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0002_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='shape',
            field=models.CharField(choices=[('circle', 'Круг'), ('square', 'Квадрат'), ('rectangle', 'Прямоугольник')], default='Circle', max_length=20, verbose_name='Форма'),
        ),
    ]
