# Generated by Django 4.0.4 on 2022-05-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0003_cake_shape'),
        ('cakes_store', '0003_rename_customer_address_order_order_address_and_more'),
    ]

    operations = [
    ]
