# Generated by Django 4.0.4 on 2022-05-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0003_rename_customer_address_order_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cakes_store.order', verbose_name='Заказ'),
        ),
    ]
