# Generated by Django 4.0.4 on 2022-05-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0004_alter_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cakes_store.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cake',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_cake', to='cakes_store.cake', verbose_name='Торт'),
        ),
    ]
