# Generated by Django 4.0.4 on 2022-05-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0004_merge_20220509_1651'),
        ('cakes_store', '0005_remove_customer_order_order_customer_and_more'),
    ]

    operations = [
    ]
