# Generated by Django 4.0.4 on 2022-05-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0006_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.CharField(choices=[('Blackberry', 'Ежевика'), ('Raspberry', 'Малина'), ('Blueberry', 'Голубика'), ('Strawberry', 'Клубника')], max_length=20, verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.CharField(choices=[('Pistachios', 'Фисташки'), ('Meringue', 'Безе'), ('Hazelnuts', 'Фундук'), ('Pecan', 'Пекан'), ('Marshmallow', 'Маршмеллоу'), ('Marzipan', 'Марципан')], max_length=20, verbose_name='Декор'),
        ),
    ]
