# Generated by Django 4.0.4 on 2022-05-10 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0007_delete_testmodel_alter_customer_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
