# Generated by Django 4.0.4 on 2022-05-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0009_alter_customer_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='user',
        ),
    ]
