# Generated by Django 4.0.4 on 2022-05-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0007_alter_cake_berries_alter_cake_decor'),
        ('cakes_store', '0011_rename_user_customer_customer_and_more'),
    ]

    operations = [
    ]
