# Generated by Django 4.0.4 on 2022-05-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0016_alter_order_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
