# Generated by Django 4.0.4 on 2022-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_store', '0018_order_customer_email_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Промо код'),
        ),
    ]
